version: '3'
services:
  odoo-update:
    build:
      context: .
      dockerfile: Dockerfile
    image: fabiocdo/docker-odoo:12.0
    command: autoupdate
    network_mode: host    
    volumes:
      - ~/.ssh:/home/temp/.ssh
    environment:
      PG_USER: odoo
      PG_PASSWORD: odoo
      ODOO_VERSION: 12.0
      ODOO_ENTERPRISE: 0
      PORT: 8090
      DATABASE: odoo
      DISABLE_LOGFILE: 1
      TIME_CPU: 600
      TIME_REAL: 720